controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_vinyl_new_success:
    path: /vinyl/new/{id<\d+>}
    controller: App\Controller\VinylController::new_success


vinyl_new:
    path: /vinyl/new
    controller: App\Controller\VinylController::new_vinyl

